### ISSUE TITLE
Center Map on Launch

### ISSUE THREAD

**Issue by dyzhu12** [dyzhu12/Beacon#18]
The app should center on location when launching the app and when hitting the target fab in the home screen.

**Comment by lyoung16** [comment]
![image](https://cloud.githubusercontent.com/assets/8762342/15280366/dca97e64-1afd-11e6-92d6-e1848106d441.png)

App centers on user location on launch, center location fab works. FABs are weirdly spaced because app was launched on Galaxys4 (much older version than marshmallow), but layout is fine on AVD.
